dbURI: "mongodb://{{ .Release.Name }}-mongodb/open5gs"

populate:
  enabled: true
  image:
    registry: docker.io
    repository: openverso/open5gs-dbctl
    tag: 0.10.2
    pullPolicy: IfNotPresent
  initCommands: 
    - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111
    - open5gs-dbctl add_ue_with_slice 999700000000002 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111

# Common
mongodb:
  enabled: true
  persistence:
    enabled: false
  auth:
    enabled: false
smf:
  enabled: true
  config:
    pcrf:
      enabled: false
  replicaCount: 1
  image:
    tag: 2.6.4
upf:
  enabled: false
  image:
    tag: 2.6.4
webui:
  ingress:
    enabled: false
  enabled: true
  image:
    tag: 2.6.4

# 4G
hss:
  enabled: false
  image:
    tag: 2.6.4
  mongodb:
    enabled: false
mme:
  enabled: false
  image:
    tag: 2.6.4
pcrf:
  enabled: false
  image:
    tag: 2.6.4
  mongodb:
    enabled: false
sgwc:
  enabled: false
  image:
    tag: 2.6.4
sgwu:
  enabled: false
  image:
    tag: 2.6.4

# 5G
amf:
  enabled: true
  config:
    guamiList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        amf_id:
          region: 2
          set: 1
    taiList:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          tac: [1]
    plmnList:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          s_nssai:
            - sst: 1
              sd: "0x111111"
  image:
    tag: 2.6.4
ausf:
  enabled: true
  image:
    tag: 2.6.4
bsf:
  enabled: true
  image:
    tag: 2.6.4
nrf:
  enabled: true
  image:
    tag: 2.6.4
nssf:
  enabled: true
  config:
    nsiList:
      - nrf:
          hostname: ""
          port: 7777
        sst: 1
        sd: "0x111111"
  image:
    tag: 2.6.4
pcf:
  enabled: true
  image:
    tag: 2.6.4
  mongodb:
    enabled: false
udm:
  enabled: true
  image:
    tag: 2.6.4
udr:
  enabled: true
  image:
    tag: 2.6.4
  mongodb:
    enabled: false
scp:
  enabled: false
  image:
    tag: 2.6.4
  mongodb:
    enabled: false
