# permissions for end users to view hexaueransims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hexa-ueransim-operator
    app.kubernetes.io/managed-by: kustomize
  name: hexaueransim-viewer-role
rules:
- apiGroups:
  - ueransim.coranlabs.com
  resources:
  - hexaueransims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ueransim.coranlabs.com
  resources:
  - hexaueransims/status
  verbs:
  - get
