# permissions for end users to edit hexaoais.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hexa-oai-ebpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: hexaoai-editor-role
rules:
- apiGroups:
  - oai.ebpf.coranlabs.com
  resources:
  - hexaoais
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oai.ebpf.coranlabs.com
  resources:
  - hexaoais/status
  verbs:
  - get
