# permissions for end users to edit hexaoainrues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hexa-oai-nr-ue-operator
    app.kubernetes.io/managed-by: kustomize
  name: hexaoainrue-editor-role
rules:
- apiGroups:
  - oai.nr.ue.coranlabs.com
  resources:
  - hexaoainrues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oai.nr.ue.coranlabs.com
  resources:
  - hexaoainrues/status
  verbs:
  - get
