apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hexa-free5gc-eupf-cp-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
