apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.releaseName }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: access-net
  namespace: {{ .Values.namespace }}
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "{{ .Values.network.master }}",
    "ipam": {
      "type": "{{ .Values.network.ipamType }}"
    },
    "capabilities": {
      "mac": {{ .Values.network.capabilities.mac }}
    }
  }'

